### ISSUE TITLE
WebUI suddenly giving 'No module named 'sox'

### ISSUE THREAD

**Issue by WanderingError** [SociallyIneptWeeb/AICoverGen#137]
Hihi, I use the WebUI as I don't have an Nvidia GPU and usually it works great (minus some disconnecting here and there but think that's on Google), but today I clicked "Run all" and let it run, and the output on the final cell read this

`Timer: 00:04:08Traceback (most recent call last):
  File "/content/HRVC/src/webui.py", line 10, in <module>
    from main import song_cover_pipeline
  File "/content/HRVC/src/main.py", line 15, in <module>
    import sox
ModuleNotFoundError: No module named 'sox'
Timer: 00:04:09`

This hasn't happened before, any ideas what's going on?

**Comment by niksu37** [comment]
Same issue here, cannot open gradio

**Comment by StevenBeach33** [comment]
I tried downgrade pip version, it can open gradio, but can't operated properly

**Comment by cutiepie030** [comment]
Same issue here....

**Comment by SociallyIneptWeeb** [comment]
It should be working now, I have updated the colab notebook with a pip version specification.

**Comment by WanderingError** [comment]
> It should be working now, I have updated the colab notebook with a pip version specification.

It does seem to work now, I have to be away from my computer shortly but I was at least able to get the UI running again

**Comment by eungss** [comment]
thank you very much

**Comment by Serj-Levonyuk** [comment]
The error is back:
```
Timer: 00:01:58Traceback (most recent call last):
  File "/content/HRVC/src/webui.py", line 10, in <module>
    from main import song_cover_pipeline
  File "/content/HRVC/src/main.py", line 15, in <module>
    import sox
ModuleNotFoundError: No module named 'sox'
```

<details><summary>"Install requirements" log:</summary>
<p>

Timer: 00:00:02Requirement already satisfied: pip==23.3.1 in /usr/local/lib/python3.12/dist-packages (23.3.1)
Timer: 00:01:05  Installing build dependencies ... done
  Getting requirements to build wheel ... done
Timer: 00:01:31  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Timer: 00:01:36ERROR: Could not find a version that satisfies the requirement faiss-cpu==1.7.3 (from versions: 1.8.0, 1.8.0.post1, 1.9.0, 1.9.0.post1, 1.10.0, 1.11.0, 1.11.0.post1, 1.12.0, 1.13.0, 1.13.1, 1.13.2)
ERROR: No matching distribution found for faiss-cpu==1.7.3
Timer: 00:01:43Collecting gradio-client==0.8.1
  Using cached gradio_client-0.8.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (2025.3.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.19.3 in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (1.3.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (26.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (4.15.0)
Requirement already satisfied: websockets<12.0,>=10.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.8.1) (11.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (3.20.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (1.2.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.3->gradio-client==0.8.1) (0.21.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->gradio-client==0.8.1) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->gradio-client==0.8.1) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->gradio-client==0.8.1) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->gradio-client==0.8.1) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->gradio-client==0.8.1) (0.16.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.19.3->gradio-client==0.8.1) (8.3.1)
Using cached gradio_client-0.8.1-py3-none-any.whl (305 kB)
Timer: 00:01:53Installing collected packages: gradio-client
  Attempting uninstall: gradio-client
    Found existing installation: gradio_client 0.6.1
    Uninstalling gradio_client-0.6.1:
      Successfully uninstalled gradio_client-0.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 3.48.0 requires gradio-client==0.6.1, but you have gradio-client 0.8.1 which is incompatible.
Successfully installed gradio-client-0.8.1
Timer: 00:01:59Requirement already satisfied: gradio==3.48.0 in /usr/local/lib/python3.12/dist-packages (3.48.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (5.5.0)
Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (0.123.10)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (1.0.0)
Collecting gradio-client==0.6.1 (from gradio==3.48.0)
  Using cached gradio_client-0.6.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (1.3.7)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (6.5.2)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (3.1.6)
Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (2.1.5)
Requirement already satisfied: matplotlib~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (3.10.0)
Requirement already satisfied: numpy~=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (26.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (2.2.2)
Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (10.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (0.25.1)
Requirement already satisfied: python-multipart in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (6.0.3)
Requirement already satisfied: requests~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (2.32.4)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (2.10.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (0.40.0)
Requirement already satisfied: websockets<12.0,>=10.0 in /usr/local/lib/python3.12/dist-packages (from gradio==3.48.0) (11.0.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==0.6.1->gradio==3.48.0) (2025.3.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair<6.0,>=4.2.0->gradio==3.48.0) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair<6.0,>=4.2.0->gradio==3.48.0) (2.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.14.0->gradio==3.48.0) (3.20.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.14.0->gradio==3.48.0) (1.2.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.14.0->gradio==3.48.0) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.14.0->gradio==3.48.0) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.14.0->gradio==3.48.0) (0.21.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->gradio==3.48.0) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->gradio==3.48.0) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->gradio==3.48.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->gradio==3.48.0) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->gradio==3.48.0) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.0->gradio==3.48.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio==3.48.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio==3.48.0) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.48.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.48.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.48.0) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests~=2.0->gradio==3.48.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests~=2.0->gradio==3.48.0) (2.5.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.14.0->gradio==3.48.0) (8.3.1)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi->gradio==3.48.0) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi->gradio==3.48.0) (0.0.4)
Timer: 00:02:00Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.48.0) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.48.0) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.48.0) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.48.0) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio==3.48.0) (1.17.0)
Timer: 00:02:01Using cached gradio_client-0.6.1-py3-none-any.whl (299 kB)
Timer: 00:02:12Installing collected packages: gradio-client
  Attempting uninstall: gradio-client
    Found existing installation: gradio_client 0.8.1
    Uninstalling gradio_client-0.8.1:
      Successfully uninstalled gradio_client-0.8.1
Timer: 00:02:13Successfully installed gradio-client-0.6.1
Timer: 00:02:17Looking in indexes: https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
Requirement already satisfied: ort-nightly-gpu in /usr/local/lib/python3.12/dist-packages (1.19.0.dev20240531001)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (25.12.19)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (5.29.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from ort-nightly-gpu) (1.14.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.12/dist-packages (from coloredlogs->ort-nightly-gpu) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->ort-nightly-gpu) (1.3.0)
Timer: 00:02:27Finished Installing Requirements
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,010 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
121 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Finished Updating
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sox is already the newest version (14.4.2+git20190427-2+deb11u2ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 121 not upgraded.
Finished running this cell, proceed to the next cell

</p>
</details>
